name: dictionary
version: 1.0.0+1
publish_to: none
description: A new Flutter project for Coodesh.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  get_storage: ^2.0.3
  phosphor_flutter: ^1.4.0
  build_runner: ^2.3.0
  just_audio: ^0.9.29
  collection: ^1.16.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c/MPLUSRounded1c-Light.ttf
          weight: 300
        - asset: assets/fonts/MPLUSRounded1c/MPLUSRounded1c-Regular.ttf
          style: normal
        - asset: assets/fonts/MPLUSRounded1c/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/MPLUSRounded1c/MPLUSRounded1c-Bold.ttf
          weight: 700

